services:

  resource-db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${RESOURCE_DB_NAME}
      POSTGRES_USER: ${RESOURCE_DB_USER}
      POSTGRES_PASSWORD: ${RESOURCE_DB_PASSWORD}
    volumes:
      - ./init-scripts/resource-db:/docker-entrypoint-initdb.d
    restart: unless-stopped

  song-db:
    image: postgres:17-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${SONG_DB_NAME}
      POSTGRES_USER: ${SONG_DB_USER}
      POSTGRES_PASSWORD: ${SONG_DB_PASSWORD}
    volumes:
      - ./init-scripts/song-db:/docker-entrypoint-initdb.d
    restart: unless-stopped

  resource-service:
    build: ./resource-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: ${RESOURCE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${RESOURCE_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${RESOURCE_DB_PASSWORD}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
      GATEWAY_SERVER_URL: ${GATEWAY_SERVER_URL}
      RABBITMQ_HOSTNAME: ${RABBITMQ_HOSTNAME}
      LOCALSTACK_ENDPOINT: ${LOCALSTACK_ENDPOINT}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_RESOURCES_BUCKET: ${AWS_RESOURCES_BUCKET}
    restart: unless-stopped

  song-service:
    build: ./song-service
    ports:
      - "8082-8083:8082"
    deploy:
      replicas: 2
    environment:
      SPRING_DATASOURCE_URL: ${SONG_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${SONG_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${SONG_DB_PASSWORD}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
    restart: unless-stopped

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    restart: unless-stopped

  gateway-server:
    build: ./gateway-server
    ports:
      - "8080:8080"
    environment:
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
      GATEWAY_SERVER_HOSTNAME: ${GATEWAY_SERVER_HOSTNAME}
    restart: unless-stopped

  localstack:
    image: localstack/localstack:4
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3
    volumes:
      - ./init-scripts/localstack:/etc/localstack/init/ready.d
    restart: unless-stopped

  resource-processor:
    build: ./resource-processor
    environment:
      GATEWAY_SERVER_URL: ${GATEWAY_SERVER_URL}
      RABBITMQ_HOSTNAME: ${RABBITMQ_HOSTNAME}
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped