apiVersion: 1

datasources:
  - name: prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: ${PROMETHEUS_ENDPOINT}
    isDefault: true
    editable: false
  - name: elasticsearch
    uid: elasticsearch
    type: elasticsearch
    access: proxy
    url: ${ELASTICSEARCH_ENDPOINT}
    isDefault: false
    editable: false
    jsonData:
      index: "filebeat-*"
      timeField: "@timestamp"
      logMessageField: "message"
      logLevelField: "log.level"