spring:
  application:
    name: resource-processor
  rabbitmq:
    host: "${RABBITMQ_HOSTNAME:localhost}"
    port: 5672
app:
  retry:
    max-attempts: 5
    initial-interval: 1000
    multiplier: 2.0
    max-interval: 10000
server:
  port: 8084
logging:
  level:
    com.epam.learn.rp: info
    org.springframework: info