spring:
  application.name: song-service
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/song_db}"
    username: "${SPRING_DATASOURCE_USERNAME:postgres}"
    password: "${SPRING_DATASOURCE_PASSWORD:postgres}"
server:
  port: 8081