spring:
  application:
    name: song-service
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/song_db}"
    username: "${SPRING_DATASOURCE_USERNAME:postgres}"
    password: "${SPRING_DATASOURCE_PASSWORD:postgres}"
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: "${EUREKA_SERVER_URL:http://localhost:8761/eureka}"
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: "${SONG_SERVICE_HOSTNAME:localhost}"
logging:
  level:
    com.epam.learn.ss: info
    org.springframework: info